//! Wrapper-script support: runtime command resolution for `--wrap`
//! and script generation for `--create-wrapper`.

use anyhow::{Context, Result, bail};
use std::borrow::Cow;
use std::env;
use std::ffi::{CString, OsStr};
use std::fs;
use std::io::{Read, Write};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::{MetadataExt, OpenOptionsExt};
use std::path::{Path, PathBuf};

/// Every generated wrapper starts with these exact bytes.  The prefix
/// doubles as the marker that makes a file safe to overwrite and lets
/// `--wrap` skip other wrappers during PATH resolution.
const MARKER: &[u8] = b"#!/bin/sh\n# tfil-wrapper\n";

/// Resolve the command a wrapper stands for: search PATH for an
/// executable named after `self_path`'s basename, skipping the wrapper
/// itself (compared by device/inode, so symlinked or renamed wrappers
/// are still recognized) and any other tfil wrapper.
pub fn resolve_command(self_path: &Path) -> Result<PathBuf> {
    let name = self_path
        .file_name()
        .with_context(|| format!("--wrap={}: no file name", self_path.display()))?;
    resolve_in_path(&env::var_os("PATH").unwrap_or_default(), name, self_path).with_context(|| {
        format!(
            "{}: not found in PATH (excluding wrappers)",
            name.to_string_lossy()
        )
    })
}

fn resolve_in_path(path_var: &OsStr, name: &OsStr, self_path: &Path) -> Option<PathBuf> {
    let self_id = file_id(self_path);
    env::split_paths(path_var).find_map(|dir| {
        let dir = nonempty_dir(dir);
        let cand = dir.join(name);
        (is_executable_file(&cand)
            && !(self_id.is_some() && file_id(&cand) == self_id)
            && !is_tfil_wrapper(&cand))
        .then_some(cand)
    })
}

/// Create a wrapper script at each path.  All targets are validated
/// before any file is written so a refusal leaves nothing behind.
pub fn create_wrappers(
    paths: &[PathBuf],
    force: bool,
    opts: &[String],
    fixed_args: &[String],
) -> Result<()> {
    let home = env::home_dir();
    let mut targets: Vec<PathBuf> = Vec::new();
    for path in paths {
        let path = expand_tilde(path, home.as_deref());
        if !targets.contains(&path) {
            targets.push(path);
        }
    }
    for target in &targets {
        validate_target(target, force)?;
    }
    let content = script_content(opts, fixed_args)?;
    for target in &targets {
        write_executable(target, content.as_bytes())
            .with_context(|| format!("{}: cannot write", target.display()))?;
        println!("tfil: created {}", target.display());
    }
    for target in &targets {
        warn_if_shadowed(target);
    }
    Ok(())
}

fn validate_target(target: &Path, force: bool) -> Result<()> {
    if target.file_name().is_none() {
        bail!("{}: not a file path", target.display());
    }
    match fs::symlink_metadata(target) {
        Ok(meta) if meta.is_dir() => bail!("{}: is a directory", target.display()),
        Ok(_) if !force && !is_tfil_wrapper(target) => bail!(
            "{}: exists and is not a tfil wrapper (use --force to overwrite)",
            target.display()
        ),
        _ => {}
    }
    let parent = nonempty_parent(target);
    if !parent.is_dir() {
        bail!("{}: not a directory", parent.display());
    }
    Ok(())
}

fn script_content(opts: &[String], fixed_args: &[String]) -> Result<String> {
    let mut exec_line = String::from("exec tfil --wrap=\"$0\"");
    for opt in opts {
        exec_line.push(' ');
        exec_line.push_str(&quote(opt)?);
    }
    exec_line.push_str(" --");
    for arg in fixed_args {
        exec_line.push(' ');
        exec_line.push_str(&quote(arg)?);
    }
    exec_line.push_str(" \"$@\"");
    Ok(format!(
        "{}# Generated by tfil {}.\n{}\n",
        std::str::from_utf8(MARKER).unwrap(),
        env!("CARGO_PKG_VERSION"),
        exec_line
    ))
}

fn quote(s: &str) -> Result<Cow<'_, str>> {
    shlex::try_quote(s).map_err(|_| anyhow::anyhow!("{s:?}: cannot quote for /bin/sh"))
}

fn write_executable(path: &Path, content: &[u8]) -> Result<()> {
    let name = path.file_name().unwrap().to_string_lossy();
    let tmp = nonempty_parent(path).join(format!(".{}.tfil-tmp.{}", name, std::process::id()));
    let result = (|| -> Result<()> {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o755)
            .open(&tmp)?;
        file.write_all(content)?;
        drop(file);
        fs::rename(&tmp, path)?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&tmp);
    }
    result
}

fn warn_if_shadowed(wrapper: &Path) {
    let Some(name) = wrapper.file_name() else {
        return;
    };
    let wrapper_id = file_id(wrapper);
    for dir in env::split_paths(&env::var_os("PATH").unwrap_or_default()) {
        let cand = nonempty_dir(dir).join(name);
        if !is_executable_file(&cand) {
            continue;
        }
        if wrapper_id.is_some() && file_id(&cand) == wrapper_id {
            return;
        }
        eprintln!(
            "tfil: warning: {} shadows {} in PATH",
            cand.display(),
            wrapper.display()
        );
        return;
    }
    eprintln!(
        "tfil: warning: {} is not reachable via PATH",
        wrapper.display()
    );
}

fn expand_tilde(path: &Path, home: Option<&Path>) -> PathBuf {
    let bytes = path.as_os_str().as_bytes();
    match home {
        Some(home) if bytes == b"~" => home.to_path_buf(),
        Some(home) if bytes.starts_with(b"~/") => home.join(OsStr::from_bytes(&bytes[2..])),
        _ => path.to_path_buf(),
    }
}

fn nonempty_dir(dir: PathBuf) -> PathBuf {
    if dir.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        dir
    }
}

fn nonempty_parent(path: &Path) -> &Path {
    match path.parent() {
        Some(p) if !p.as_os_str().is_empty() => p,
        _ => Path::new("."),
    }
}

fn file_id(path: &Path) -> Option<(u64, u64)> {
    fs::metadata(path).ok().map(|m| (m.dev(), m.ino()))
}

fn is_executable_file(path: &Path) -> bool {
    let Ok(meta) = fs::metadata(path) else {
        return false;
    };
    if !meta.is_file() {
        return false;
    }
    let Ok(cpath) = CString::new(path.as_os_str().as_bytes()) else {
        return false;
    };
    unsafe { libc::access(cpath.as_ptr(), libc::X_OK) == 0 }
}

fn is_tfil_wrapper(path: &Path) -> bool {
    let mut buf = [0u8; MARKER.len()];
    match fs::File::open(path) {
        Ok(mut f) => f.read_exact(&mut buf).is_ok() && buf == *MARKER,
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    fn make_executable(path: &Path, content: &str) {
        fs::write(path, content).unwrap();
        fs::set_permissions(path, fs::Permissions::from_mode(0o755)).unwrap();
    }

    #[test]
    fn expand_tilde_replaces_leading_tilde() {
        let home = Path::new("/home/knu");
        assert_eq!(expand_tilde(Path::new("~"), Some(home)), home);
        assert_eq!(
            expand_tilde(Path::new("~/bin/claude"), Some(home)),
            Path::new("/home/knu/bin/claude")
        );
        assert_eq!(
            expand_tilde(Path::new("~user/bin"), Some(home)),
            Path::new("~user/bin")
        );
        assert_eq!(
            expand_tilde(Path::new("/abs/path"), Some(home)),
            Path::new("/abs/path")
        );
        assert_eq!(expand_tilde(Path::new("~/bin"), None), Path::new("~/bin"));
    }

    #[test]
    fn script_content_starts_with_marker_and_quotes_args() {
        let content = script_content(
            &[
                "--strip-ink-fake-cursor".into(),
                "--tmux-osc-passthrough=22".into(),
            ],
            &["it's".into()],
        )
        .unwrap();
        assert!(content.as_bytes().starts_with(MARKER));

        let exec_line = content.lines().last().unwrap();
        let words = shlex::split(exec_line).unwrap();
        assert_eq!(
            words,
            [
                "exec",
                "tfil",
                "--wrap=$0",
                "--strip-ink-fake-cursor",
                "--tmux-osc-passthrough=22",
                "--",
                "it's",
                "$@",
            ]
        );
    }

    #[test]
    fn generated_content_is_recognized_as_wrapper() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("claude");
        let content = script_content(&[], &[]).unwrap();
        fs::write(&path, &content).unwrap();
        assert!(is_tfil_wrapper(&path));

        let other = dir.path().join("other");
        fs::write(&other, "#!/bin/sh\necho hi\n").unwrap();
        assert!(!is_tfil_wrapper(&other));
    }

    #[test]
    fn resolve_skips_self_and_other_wrappers() {
        let tmp = tempfile::tempdir().unwrap();
        let bin_a = tmp.path().join("a");
        let bin_b = tmp.path().join("b");
        let bin_c = tmp.path().join("c");
        for d in [&bin_a, &bin_b, &bin_c] {
            fs::create_dir(d).unwrap();
        }
        let self_path = bin_a.join("claude");
        make_executable(&self_path, "#!/bin/sh\n# tfil-wrapper\nexec tfil\n");
        let other_wrapper = bin_b.join("claude");
        make_executable(&other_wrapper, "#!/bin/sh\n# tfil-wrapper\nexec tfil\n");
        let real = bin_c.join("claude");
        make_executable(&real, "#!/bin/sh\necho real\n");

        let path_var = env::join_paths([&bin_a, &bin_b, &bin_c]).unwrap();
        let resolved = resolve_in_path(&path_var, OsStr::new("claude"), &self_path);
        assert_eq!(resolved.as_deref(), Some(real.as_path()));
    }

    #[test]
    fn resolve_follows_symlinked_self() {
        let tmp = tempfile::tempdir().unwrap();
        let bin = tmp.path().join("bin");
        let real_dir = tmp.path().join("real");
        fs::create_dir(&bin).unwrap();
        fs::create_dir(&real_dir).unwrap();
        make_executable(
            &bin.join("claude"),
            "#!/bin/sh\n# tfil-wrapper\nexec tfil\n",
        );
        std::os::unix::fs::symlink(bin.join("claude"), bin.join("gemini")).unwrap();
        let real = real_dir.join("gemini");
        make_executable(&real, "#!/bin/sh\necho real\n");

        let path_var = env::join_paths([&bin, &real_dir]).unwrap();
        let resolved = resolve_in_path(&path_var, OsStr::new("gemini"), &bin.join("gemini"));
        assert_eq!(resolved.as_deref(), Some(real.as_path()));
    }

    #[test]
    fn resolve_fails_when_only_self_exists() {
        let tmp = tempfile::tempdir().unwrap();
        let bin = tmp.path().join("bin");
        fs::create_dir(&bin).unwrap();
        let self_path = bin.join("claude");
        make_executable(&self_path, "#!/bin/sh\nexec tfil\n");

        let path_var = env::join_paths([&bin]).unwrap();
        assert_eq!(
            resolve_in_path(&path_var, OsStr::new("claude"), &self_path),
            None
        );
    }

    #[test]
    fn create_wrappers_writes_executable_and_dedups() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("claude");
        let paths = vec![target.clone(), target.clone()];
        create_wrappers(&paths, false, &["--strip-ink-fake-cursor".into()], &[]).unwrap();

        let meta = fs::metadata(&target).unwrap();
        assert_eq!(meta.permissions().mode() & 0o777, 0o755);
        assert!(is_tfil_wrapper(&target));

        // Re-creating over an existing wrapper needs no --force.
        create_wrappers(&paths, false, &[], &[]).unwrap();
    }

    #[test]
    fn create_wrappers_refuses_foreign_files_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("claude");
        fs::write(&target, "real binary").unwrap();

        let err = create_wrappers(std::slice::from_ref(&target), false, &[], &[]).unwrap_err();
        assert!(err.to_string().contains("not a tfil wrapper"));
        assert_eq!(fs::read_to_string(&target).unwrap(), "real binary");

        create_wrappers(std::slice::from_ref(&target), true, &[], &[]).unwrap();
        assert!(is_tfil_wrapper(&target));
    }

    #[test]
    fn create_wrappers_validates_all_before_writing_any() {
        let tmp = tempfile::tempdir().unwrap();
        let good = tmp.path().join("good");
        let bad = tmp.path().join("bad");
        fs::write(&bad, "real binary").unwrap();

        assert!(create_wrappers(&[good.clone(), bad], false, &[], &[]).is_err());
        assert!(!good.exists());
    }
}
